### PR TITLE
test: Improve Test Coverage for packages/web3/src/block #452

### LINKED ISSUE #452: Improve Test Coverage for `packages/web3/src/block`
This issue aims to improve the test coverage for this folder by:  
1. Identifying untested or under-tested functions and classes.  
2. Writing additional unit tests to cover edge cases and scenarios.

### PR DESCRIPTION
**Pull request by ShantelPeters**
# Additional tests
1. BlockSubscription class (main implementation):

   - Testing the polling mechanism with different time intervals
   - Cache management and expiration
   - Handling of multiple chains in block responses
   - Error handling during polling
   - Missing blocks detection and handling

2. BlockSubscriptionBase class:
   - Edge cases for undefined reorgCallback
   - Handling of invalid block structures
   - Parent hash calculation with edge cases

4. Key scenarios that should be tested:
   - Timestamp handling (future timestamps, expired timestamps)
   - Network errors and retry behavior
   - Block ordering and sorting
   - Chain reorganization with various depths
   - Cache management with concurrent updates
   
   
Resolves #452

### CODE REVIEW

**Comment by h0ngcha0** [comment]
Hey, thanks for the contribution.

Please make sure that the tests pass, right now several of them are failing. 

```bash
> npm run test -- block.test.ts --collectCoverageOnlyFrom ''
.....
Test Suites: 1 failed, 1 total
Tests:       3 failed, 7 passed, 10 total
```

**Comment by ShantelPeters** [comment]
fixed.

**Comment by ShantelPeters** [comment]
Hi, ran it and it's not failing

```
npm run test


> @alephium/web3@1.9.0 test
> jest -i --config ./jest-config.json

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-0, new hash: main-0

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0, new hashes: main-0

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: main-2

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes: main-0,main-1,main-2

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: main-1

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes: main-0,main-1

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: common

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes:

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 1, orphan hash: orphan, new hash: new

      at TestBlockSubscription.handleReorg (src/block/block.ts:54:13)

 PASS  src/block/block.test.ts (45.133 s)
  block subscription
    ✓ should handle reorg(1 orphan block) (161 ms)
    ✓ should handle reorg(multiple orphan blocks) (23 ms)
    ✓ should handle reorg to short chain (16 ms)
  BlockSubscription implementation
    ✓ should handle empty blocks response (12 ms)
    ✓ should handle cache expiration correctly (4 ms)
    ✓ should handle missing blocks correctly (5 ms)
  BlockSubscriptionBase edge cases
    ✓ should handle undefined reorgCallback (10 ms)
    ✓ should handle empty deps array (96 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        48.169 s
Ran all test suites.
```

**Comment by ShantelPeters** [comment]
Second run

```
npm run test

> @alephium/web3@1.9.0 test
> jest -i --config ./jest-config.json

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-0, new hash: main-0

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0, new hashes: main-0

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: main-2

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes: main-0,main-1,main-2

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: main-1

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes: main-0,main-1

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 0, orphan hash: fork-2, new hash: common

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:54:13)

  console.info
    orphan hashes: fork-0,fork-1,fork-2, new hashes:

      at BlockSubscriptionTest.handleReorg (src/block/block.ts:83:13)

  console.info
    reorg occur in chain 0 -> 1, orphan hash: orphan, new hash: new

      at TestBlockSubscription.handleReorg (src/block/block.ts:54:13)

 PASS  src/block/block.test.ts (5.273 s)
  block subscription
    ✓ should handle reorg(1 orphan block) (59 ms)
    ✓ should handle reorg(multiple orphan blocks) (5 ms)
    ✓ should handle reorg to short chain (7 ms)
  BlockSubscription implementation
    ✓ should handle empty blocks response (3 ms)
    ✓ should handle cache expiration correctly (2 ms)
    ✓ should handle missing blocks correctly (2 ms)
  BlockSubscriptionBase edge cases
    ✓ should handle undefined reorgCallback (3 ms)
    ✓ should handle empty deps array (46 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        5.423 s, estimated 6 s
Ran all test suites.
```

**Pull request closed without merging**
