### PR TITLE
Bump version to v0.14.7

### PR DESCRIPTION
**Pull request by h0ngcha0**

### CODE REVIEW

**Comment by polarker** [comment]
Maybe we should release `0.15.0` since there are multiple breaking changes introduced.

**Comment by h0ngcha0** [comment]
> Maybe we should release `0.15.0` since there are multiple breaking changes introduced.

Sounds good :+1:

**Comment by polarker** [comment]
@h0ngcha0 Let's update the SDK version in template

**Comment by polarker** [comment]
Let's maybe release 0.15.0 once the other two PRs are merged

**Comment by h0ngcha0** [comment]
> Let's maybe release 0.15.0 once the other two PRs are merged

Sounds good :+1:

**Comment by polarker** [comment]
@h0ngcha0 we need to update these dependencies too: https://github.com/alephium/alephium-web3/blob/master/packages/cli/templates/base/package.json#L18-L21

**Pull request merged**
