### PR TITLE
Rename desktop wallet deep link redirect

### PR DESCRIPTION
**Pull request by nop33**
Related to https://github.com/alephium/alephium-frontend/issues/164

### CODE REVIEW

**Review by Lbqds — APPROVED** [review]
LGTM, thanks!

**Comment by nop33** [comment]
Let's please wait for @mvaivre to confirm whether he agrees with this change or not, before merging 🙏 .

**Review by mvaivre — COMMENTED** [review]
Is it considered ok to use a dash in the URL's protocol part? If yes, LGTM!

**Comment by nop33** [comment]
Closing due to this decision: https://github.com/alephium/alephium-web3/pull/282#issuecomment-1849481755

**Pull request closed without merging**
